# Generated by Django 5.0.6 on 2024-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='images/students')),
                ('roll_no', models.IntegerField(unique=True)),
                ('semester', models.CharField(max_length=10)),
                ('gpa', models.FloatField(max_length=10)),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('phone_num', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='images/employees'),
        ),
    ]
